spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

#mybatis
mybatis:
  type-aliases-package: com.pti.mall.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080